// Single mock data export aligned 100% with the finalized MongoDB schema for trees
export const treesMockData = {
  statistics: {
    totalTrees: 8450,
    healthyTrees: 7850,
    monitoringTrees: 420,
    diseasedTrees: 180,
  },
  filters: {
    farms: [
      { farm_id: "f1", farm_name: "Chanthaburi Gold" },
      { farm_id: "f2", farm_name: "Rayong Sweet" },
      { farm_id: "f3", farm_name: "Chumphon Valley" },
    ],
    zones: [
      { zone_id: "z1", zone_name: "Zone A1" },
      { zone_id: "z2", zone_name: "Zone A2" },
      { zone_id: "z3", zone_name: "Zone B1" },
      { zone_id: "z4", zone_name: "Zone C1" },
    ],
    statuses: ["All", "Healthy", "Monitoring", "Diseased"],
  },
  table: {
    rows: [
      {
        _id: "t1",
        tree_code: "TR-001",
        farm_id: "f1",
        zone_id: "z1",
        variety: "Ri6",
        planting_date: "2022-04-12",
        tree_age: 4,
        status: "Healthy",
        last_inspection: "2026-06-15",
        qr_code: "QR-TR001-A1",
        created_at: "2022-04-12",
      },
      {
        _id: "t2",
        tree_code: "TR-002",
        farm_id: "f1",
        zone_id: "z2",
        variety: "Monthong",
        planting_date: "2021-05-18",
        tree_age: 5,
        status: "Monitoring",
        last_inspection: "2026-06-20",
        qr_code: "QR-TR002-A2",
        created_at: "2021-05-18",
      },
      {
        _id: "t3",
        tree_code: "TR-003",
        farm_id: "f2",
        zone_id: "z3",
        variety: "Ri6",
        planting_date: "2020-02-22",
        tree_age: 6,
        status: "Healthy",
        last_inspection: "2026-05-10",
        qr_code: "QR-TR003-B1",
        created_at: "2020-02-22",
      },
      {
        _id: "t4",
        tree_code: "TR-004",
        farm_id: "f3",
        zone_id: "z4",
        variety: "Monthong",
        planting_date: "2019-11-05",
        tree_age: 7,
        status: "Diseased",
        last_inspection: "2026-07-02",
        qr_code: "QR-TR004-C1",
        created_at: "2019-11-05",
      },
    ],
  },
  pagination: {
    page: 1,
    totalPages: 1,
    totalRecords: 4,
  },
};
